[package]
name = "csv-to-json-array-map-with-timestamp"
group = "infinyon"
version = "0.1.0"
apiVersion = "0.1.0"
description = ""
license = "Apache-2.0"
visibility = "private"

[[params]]
name = "timestamp"
description = "Timestamp field for conversion"
